openapi: 3.0.1
info:
  title: diff-bdsm-sys
  description: API Definition of diff-bdsm-sys
  version: 1.0.0
servers:
- url: http://localhost:8290/bdsm
paths:
  /pos/{code}:
    get:
      parameters:
      - name: code
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
