openapi: 3.0.1
info:
  title: spike-mock
  description: API Definition of spike-mock
  version: 1.0.0
servers:
- url: http://localhost:8290/spike-mock
paths:
  /:
    get:
      responses:
        default:
          description: Default response
