openapi: 3.0.1
info:
  title: bankapi-sys
  description: API Definition of bankapi-sys
  version: 1.0.0
servers:
- url: http://localhost:8290/bankapi-sys
paths:
  /:
    get:
      responses:
        default:
          description: Default response
