openapi: 3.0.1
info:
  title: diff-kis1s-sys
  description: API Definition of diff-kis1s-sys
  version: 1.0.0
servers:
- url: http://localhost:8290/diff-kis1s-sys
paths:
  /1c/get-tt/{code}:
    get:
      parameters:
      - name: code
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
