openapi: 3.0.1
info:
  title: diff-tt-prc
  description: API Definition of diff-tt-prc
  version: 1.0.0
servers:
- url: http://localhost:8290/default/1.0.0
paths:
  /tt-check:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /tt-cbo-compare:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
