openapi: 3.0.1
info:
  title: spike-sys
  description: API Definition of spike-sys
  version: 1.0.0
servers:
- url: http://localhost:8290/spike-sys
paths:
  /:
    get:
      responses:
        default:
          description: Default response
